### ISSUE TITLE
Extremely slow on google colab with 1 hour audio

### ISSUE THREAD

**Issue by 9xcoder** [NextAudioGen/ultimatevocalremover_api#11]
I tried this repo on google colab,
it worked extremely slow with 1 hour audio, I tried waiting for about 1 hour 30 minutes but it didn't seem to work and then google closed google my colab runtime.

**Comment by MohannadEhabBarakat** [comment]
In my tests, it was as fast as the GUI version. Make sure to use GPU and there is some workaround on collab to make sessions stay much longer
